### ISSUE TITLE
Add further options: 3" reels, 24/48 & 16/48, 15/16ips

### ISSUE THREAD

**Issue by kfrn** [kfrn/reel-time#10]
Per Corey Bailey:
- Diameter: 3" - **DONE** (91be831a5ee7150cfbe9cbf71953f5fa2ed8e2fd)
- ~Type: 4-channel (quadraphonic)~ moved to #5 

Per Shai Drori & Brecht Declercq (AMIA-L)
- different sampling frequencies and bit depths, e.g. 16/48 or 24/48. - **DONE** (ea109c7d81c89de1bfdc2122bc0b2ce3975eab56)

Per  Stefano S. Cavaglieri (IASA-L):
- additional replay speed of 15/16 ips (0.9375ips) - **DONE** (0a33cd7)

**Comment by kfrn** [comment]
Added recording speed of 15/16ips in 0a33cd7bfebaf2813a7a95c8b635793d647580f5

**Comment by kfrn** [comment]
Added different bit-depth/sampling-freq combos as dropdown on the total row in e3f3181eb60f19c49a4e61a37db5773cf2e1ba23.

![file_options](https://user-images.githubusercontent.com/16832997/35187920-7d4769d0-fe91-11e7-810a-2fadd54d2e04.png)

Not ready for deploy yet, since I should also update the text on the info page.

**Comment by retokromer** [comment]
What do you mean by «tailleur»?

**Comment by retokromer** [comment]
P.S. – _metric_ and _imperial_ needs also to be translated.

**Comment by kfrn** [comment]
Oppps - typo, I meant "taille" not "tailleur"! It's probably because I sew, lol. I need to remember to check these things against dictionary/google translate. But let me know if "taille" is not the right word to refer to file size.

En français, dirait-on 'metrique' ou 'SI'? Pour "imperial", ce qui est mieux, "impérial" ou "britannique"?
IT: _metrico_ e _imperiale_?

As always, thank you, @retokromer !

**Comment by retokromer** [comment]
- «taille» is very fine
- strictly speaking, «metric» and «SI» are not identical (I guess, «SI» is correct, but I will check what is more widely used)
- I have to check about «impérial» and «britannique» (I don’t use that in my daily life ;-)
- I will check also the Italian saying

**Comment by retokromer** [comment]
- FR: The most used terms seems to be _unités impériales_ and _unités métriques_. That’s probably too long, therefore I would suggest to use just the adjective in singular _impérial_ and _métrique_.
- IT: The most used terms seems to be _sistemi anglosassoni_ (plural!) and _sistema internazionale_, but I would suggest _imperiale_ and _metrico_ as well.

**Comment by kfrn** [comment]
Thanks! I found various terms, but wasn't sure what was idiomatic, and of course here I prefer a short term. Since I'm using adjectives in English too, those match nicely. Fixed in a60c8571aa0e731fd6c3102de94ae66acf4215ad

(Haha, yes, in my country we are sensible and use the metric system, not "the one with inches and feet" aka "imperial" :wink: ).

**Comment by kfrn** [comment]
Different sampling frequencies/bit-depths now done as of ea109c7d81c89de1bfdc2122bc0b2ce3975eab56

**Comment by kfrn** [comment]
3" reels now added in b64e7d1  
Will double-check with Corey Bailey!
