### ISSUE TITLE
Make mobile-friendly

### ISSUE THREAD

**Issue by kfrn** [kfrn/reel-time#13]
How to display something with a horizontal tabular format on mobile ... design problem!

**Comment by retokromer** [comment]
A Möbius strip (or, for richer people, a Klein bottle) might help! ;-)

**Comment by kfrn** [comment]
- [One approach](https://css-tricks.com/examples/ResponsiveTables/responsive.php) that looks promising (found [here](https://ux.stackexchange.com/questions/35302/responsive-design-how-to-deal-with-wide-html-tables))

**Comment by retokromer** [comment]
Yes, something like this could be a good solution!

**Comment by kfrn** [comment]
Just over a year later ... finally complete!

**Comment by kfrn** [comment]
Hmm, I built and deployed the latest version, but there are some errors in the console regarding the service worker. Looks like I have some debugging to do ...

**Comment by kfrn** [comment]
And now fixed! :tada:

**Comment by retokromer** [comment]
Yes, not it works fine! Thank you!
